baseURL = "/"
languageCode = "en-us"
title = "Zander Work"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Zander Work"
  keywords = "homepage, blog, development, programming, security, cybersecurity, hacking, pwning, ctf"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  homeSubtitle = "CS/Security Student"

  [[params.social]]
    name = "email"
    url = "mailto:zander@zanderwork.com"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/zzzanderw"
  [[params.social]]
    name = "github"
    url = "https://github.com/zzzanderw"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/zanderwork/"
  [[params.social]]
    name = "keybase"
    url = "https://keybase.io/zzzanderw"
  [[params.social]]
    name = "ctftime"
    url = "https://ctftime.org/team/12858"

  title = "Zander Work"
  subtitle = ""
  keywords = "homepage, blog, development, programming, security, cybersecurity, hacking, pwning, ctf"
  copyright = "Flag icon made by Smashicons"
  readOtherPosts = "Read other posts"

  [params.logo]
    logoText = "cd /home/zanderwork"
    logoHomeLink = "/" 

[languages]
  [languages.en]
    copyright = "Flag icon made by Smashicons"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume.pdf"
